default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cineroom_development

test:
  <<: *default
  database: cineroom_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

# SolidCable configuration for Rails 8
cable:
  development:
    <<: *default
    database: cineroom_development
  test:
    <<: *default
    database: cineroom_test
  production:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

# SolidCache configuration for Rails 8
cache:
  development:
    <<: *default
    database: cineroom_development
  test:
    <<: *default
    database: cineroom_test
  production:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

# SolidQueue configuration for Rails 8
queue:
  development:
    <<: *default
    database: cineroom_development
  test:
    <<: *default
    database: cineroom_test
  production:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
